let User,CustomErrorHandler;_f39‍.x([["default",()=>_f39‍.o]]);_f39‍.w("../../Models",[["User",["User"],function(v){User=v}]]);_f39‍.w("../../Services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
   async me(req,res,next){
        try{

            const user = await await User.findOne({_id: req.user._id}).select('-password -updatedAt -__v');
            if(!user){
                return next(CustomErrorHandler.NotFound());

            }
            res.json(user);

        }catch(err){
            return next(err);

        }

    }

}

_f39‍.d(userController);